/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function Blender(props) {
  const { nodes, materials } = useGLTF('./model/blender.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 1, 0.35]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials.blenderOrange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials['white.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_2.geometry}
          material={materials.blenderDark}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./model/Blender.glb')
export default Blender

