/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useMatcapTexture } from '@react-three/drei'
import { param } from '../param.js'
import Typo from "../Mesh/Typo.jsx"
function CSS(props) {
  const { nodes, materials } = useGLTF('./model/CSS.glb')
  const [matcapTexture] = useMatcapTexture(param.matcapWhite, 256)
  return (
    <group {...props} dispose={null}>
      <Typo font={"Dinish_Condensed_Regular"} size={0.8} position={[-0.7, -0.8, 0]} matcap={matcapTexture} height={0.3} text={"CSS"} />
      <mesh
        geometry={nodes.cssbg.geometry}
        material={materials.css}
        scale={[1.08, 1.08, 0.236]}
      />
    </group>
  )
}

useGLTF.preload('./model/CSS.glb')
export default CSS