/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, Html } from '@react-three/drei'

function HtmlM(props) {
  const { nodes, materials } = useGLTF('./model/HTML.glb')
  return (
    <group {...props} dispose={null}>
      <Html center transform position={[0, 1.4, 0]}>
        <p className='skill-title' style={{ opacity: props.opacity ? 1 : 0 }}>HTML5</p>
      </Html>
      <group position={[0, 0, 0.355]} scale={[1, 1.146, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={materials.blenderOrange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_1.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_2.geometry}
          material={materials.htmlOrange}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./model/HTML.glb')
export default HtmlM