/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useMatcapTexture } from '@react-three/drei'
import { param } from '../param.js'
import Typo from "../Mesh/Typo.jsx"

function JS(props) {
  const [matcapTexture] = useMatcapTexture(param.matcapBlack, 256)
  const { nodes, materials } = useGLTF('./model/JS.glb')
  return (
    <group {...props} dispose={null}>
      <Typo font={"Neutra_Book"} size={0.8} position={[-0.3, -0.8, 0]} matcap={matcapTexture} height={0.3} text={"JS"} />
      <mesh
        geometry={nodes.JS.geometry}
        material={materials.js}
        scale={[1, 1, 0.219]}
      />
    </group>
  )
}

useGLTF.preload('./model/JS.glb')
export default JS