/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, Html, Mask, useMatcapTexture } from '@react-three/drei'
import MobileNav from './MobileNav'

export default function Mobile(props) {
  const [matcapTexture] = useMatcapTexture(props.matcap, 256)
  const { nodes, materials } = useGLTF('./model/mobile.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        scale={[0.211, 1.057, 1.057]}
      >
        <meshMatcapMaterial matcap={matcapTexture} />
      </mesh>
      <Mask id={1} colorWrite={false} depthWrite={false}
        geometry={nodes.screen.geometry}
        position={[0, 0, 0]}>
        <Html position-x={0} className="content-wrapper" rotation-y={Math.PI / 2} scale={0.2} transform >
          <MobileNav src={props.src} content={props.content} />
        </Html>
      </Mask>
    </group>
  )
}

useGLTF.preload('./model/mobile.glb')