/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, forwardRef } from 'react'
import { useGLTF, Html, Mask, useMatcapTexture } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import MobileNav from './MobileNav'

const Mobile = forwardRef(function Mobile(props, ref) {
  const [matcapTexture] = useMatcapTexture(props.matcap, 256)
  const { nodes, materials } = useGLTF('./model/mobile.glb')
  const mobile = useRef()

  useFrame((state, delta) => {
    if(mobile.current && props.redSign){
      mobile.current.rotation.y = (Math.sin(state.clock.elapsedTime)) * 0.3
      mobile.current.rotation.x = (Math.sin(state.clock.elapsedTime)) * 0.3
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh ref={mobile}
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        scale={[0.211, 1.057, 1.057]}
      >
        <meshMatcapMaterial matcap={matcapTexture} />
      </mesh>
      {!props.redSign &&
      <Mask id={1} colorWrite={false} depthWrite={false}
        geometry={nodes.screen.geometry}
        position={[0, -0.001, 0]}>
        <Html position-x={0} className="content-wrapper" rotation-y={Math.PI / 2} scale={0.2} transform ref={ref}>
          <MobileNav src={props.src} content={props.content} />
        </Html>
      </Mask>}
      <mesh visible = {!!props.redSign} 
        geometry={nodes.Torus001.geometry}
        material={materials.red}
        position={[0.568, 0, 0]}
        rotation={[Math.PI / 4, 0, -Math.PI / 2]}
        scale={1.221}
      />
    </group>
  )
})

useGLTF.preload('./model/mobile.glb')
export default Mobile