/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function Vue(props) {
  const { nodes, materials } = useGLTF('./model/vue.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.183]} scale={[1, 1, 0.65]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.vueNavy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials['vueGreen.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./model/vue.glb')
export default Vue

