/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { param } from '@/lib/param'
import Typo from "@/models/mesh/Typo"

function CSS(props) {
  const { nodes, materials } = useGLTF('./model/CSS.glb')
  return (
    <group {...props} dispose={null}>
      <Typo font={"Dinish_Condensed_Regular"} size={0.8} position={[-0.7, -0.8, 0]} color={param.white} height={0.3} text={"CSS"} />
      <mesh
        geometry={nodes.cssbg.geometry}
        material={materials.css}
        scale={[1.08, 1.08, 0.236]}
      />
    </group>
  )
}

useGLTF.preload('./model/CSS.glb')
export default CSS