/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function DE(props) {
  const { nodes, materials } = useGLTF('/model/DE.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.133]} scale={[1, 1, 0.57]}>
        <mesh
          geometry={nodes.switch002.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.switch002_1.geometry}
          material={materials.red}
        />
        <mesh
          geometry={nodes.switch002_2.geometry}
          material={materials.yellow}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/model/DE.glb')
export default DE

