/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function EN(props) {
  const { nodes, materials } = useGLTF('./model/EN.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['switch'].geometry}
        material={materials.white}
        scale={[1, 1, 0.57]}
      />
      <group scale={[1.02, 1.02, 0.581]}>
        <mesh
          geometry={nodes.switch003.geometry}
          material={materials.red}
        />
        <mesh
          geometry={nodes.switch003_1.geometry}
          material={materials.navy}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./model/EN.glb')
export default EN


