/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { param } from '@/lib/param'
import Typo from "@/models/mesh/Typo"

function JS(props) {
  const { nodes, materials } = useGLTF('/model/JS.glb')
  return (
    <group {...props} dispose={null}>
      <Typo font={"Neutra_Book"} size={0.8} position={[-0.3, -0.8, 0]} color={param.white} height={0.3} text={"JS"} />
      <mesh
        geometry={nodes.JS.geometry}
        material={materials.js}
        scale={[1, 1, 0.219]}
      />
    </group>
  )
}

useGLTF.preload('/model/JS.glb')
export default JS