/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function KR(props) {
  const { nodes, materials } = useGLTF('/model/KR.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['switch'].geometry}
        material={materials.white}
        scale={[1, 1, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taekuk.geometry}
        material={materials.KO}
        position={[0, 0, 0.385]}
        scale={[0.463, 0.463, 0.264]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Taekuk001.geometry}
        material={materials.KO}
        position={[0, 0, -0.438]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.463, 0.463, 0.264]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.black}
        position={[-0.595, 0.397, 0.253]}
        rotation={[0, 0, 2.553]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.black}
        position={[-0.67, 0.446, 0.253]}
        rotation={[0, 0, 2.553]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.black}
        position={[-0.521, 0.347, 0.253]}
        rotation={[0, 0, 2.553]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.black}
        position={[0.658, -0.316, 0.253]}
        rotation={[0, 0, 2.55]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.black}
        position={[-0.674, -0.449, 0.253]}
        rotation={[0, 0, -2.551]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.black}
        position={[-0.527, -0.35, 0.253]}
        rotation={[0, 0, -2.551]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.black}
        position={[0.466, -0.444, 0.253]}
        rotation={[0, 0, 2.55]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.black}
        position={[-0.66, -0.311, 0.253]}
        rotation={[0, 0, -2.551]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.black}
        position={[0.539, -0.493, 0.253]}
        rotation={[0, 0, 2.55]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.black}
        position={[0.585, -0.267, 0.253]}
        rotation={[0, 0, 2.55]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials.black}
        position={[-0.541, -0.488, 0.253]}
        rotation={[0, 0, -2.551]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials.black}
        position={[0.731, -0.365, 0.253]}
        rotation={[0, 0, 2.55]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.black}
        position={[0.612, -0.542, 0.253]}
        rotation={[0, 0, 2.55]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials.black}
        position={[0.586, 0.259, 0.253]}
        rotation={[0, 0, -2.561]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials.black}
        position={[0.469, 0.438, 0.253]}
        rotation={[0, 0, -2.561]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials.black}
        position={[0.618, 0.536, 0.253]}
        rotation={[0, 0, -2.561]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials.black}
        position={[0.735, 0.357, 0.253]}
        rotation={[0, 0, -2.561]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials.black}
        position={[0.602, 0.397, 0.253]}
        rotation={[0, 0, -2.561]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials.black}
        position={[-0.595, 0.397, 0.253]}
        rotation={[0, 0, 2.553]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials.black}
        position={[0.599, 0.397, -0.307]}
        rotation={[Math.PI, 0, -0.589]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.black}
        position={[0.673, 0.446, -0.307]}
        rotation={[Math.PI, 0, -0.589]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials.black}
        position={[0.525, 0.347, -0.307]}
        rotation={[Math.PI, 0, -0.589]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials.black}
        position={[-0.655, -0.316, -0.307]}
        rotation={[Math.PI, 0, -0.592]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials.black}
        position={[0.677, -0.449, -0.307]}
        rotation={[-Math.PI, 0, 0.59]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials.black}
        position={[0.53, -0.35, -0.307]}
        rotation={[-Math.PI, 0, 0.59]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.black}
        position={[-0.463, -0.444, -0.307]}
        rotation={[Math.PI, 0, -0.592]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials.black}
        position={[0.663, -0.311, -0.307]}
        rotation={[-Math.PI, 0, 0.59]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials.black}
        position={[-0.536, -0.493, -0.307]}
        rotation={[Math.PI, 0, -0.592]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.black}
        position={[-0.582, -0.267, -0.307]}
        rotation={[Math.PI, 0, -0.592]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials.black}
        position={[0.545, -0.488, -0.307]}
        rotation={[-Math.PI, 0, 0.59]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials.black}
        position={[-0.728, -0.365, -0.307]}
        rotation={[Math.PI, 0, -0.592]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials.black}
        position={[-0.609, -0.542, -0.307]}
        rotation={[Math.PI, 0, -0.592]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials.black}
        position={[-0.582, 0.259, -0.307]}
        rotation={[-Math.PI, 0, 0.581]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials.black}
        position={[-0.466, 0.438, -0.307]}
        rotation={[-Math.PI, 0, 0.581]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials.black}
        position={[-0.615, 0.536, -0.307]}
        rotation={[-Math.PI, 0, 0.581]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials.black}
        position={[-0.732, 0.357, -0.307]}
        rotation={[-Math.PI, 0, 0.581]}
        scale={[-0.03, -0.093, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials.black}
        position={[-0.598, 0.397, -0.307]}
        rotation={[-Math.PI, 0, 0.581]}
        scale={[-0.03, -0.2, -0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials.black}
        position={[0.599, 0.397, -0.307]}
        rotation={[Math.PI, 0, -0.589]}
        scale={[-0.03, -0.2, -0.24]}
      />
    </group>
  )
}

useGLTF.preload('/model/KR.glb')
export default KR