/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function LipReading(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./model/mouth.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
    actions[names[1]].reset().fadeIn(0.5).play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="bottom"
          castShadow
          receiveShadow
          geometry={nodes.bottom.geometry}
          material={materials.red}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.451, 0.451, 1.307]}
        />
        <mesh
          name="top"
          castShadow
          receiveShadow
          geometry={nodes.top.geometry}
          material={materials.red}
          rotation={[Math.PI, -1.563, Math.PI]}
          scale={[0.465, 0.465, 1.348]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./model/mouth.glb')