/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, forwardRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { param } from '@/lib/param'

const Mobile = forwardRef(function Mobile(props, ref) {
  const { nodes, materials } = useGLTF('/model/mobileRect.glb')
  const mobile = useRef()

  return (
    <group {...props} dispose={null} >
      <group ref={mobile}>
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.Material}
          scale={[0.211, 1.057, 1.03]}>
          <meshStandardMaterial color={props.color} />
        </mesh>
        <mesh
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
        >
          <meshStandardMaterial color={props.color} />
        </mesh>
      </group>
        <group>
          <mesh
            geometry={nodes.Cube006.geometry} position={[0.093, 0, 0]}
            material={materials['Material.001']}
            scale={[0.902, 0.95, 0.902]}>
            <meshStandardMaterial color={param.black} opacity={props.opacity} transparent />
          </mesh>
          <Html ref={ref} position-x={-0.01} className="iframe-wrapper-rect" rotation-y={Math.PI / 2} scale={0.2} transform>
            <iframe className="iframe-wrapper-rect" src={props.src} />
          </Html>
        </group>
    </group>
  )
})

useGLTF.preload('/model/mobileRect.glb')
export default Mobile