/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function NoteTaking(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model/notes.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
  })
  return (
    <group ref={group} {...props} dispose={null} rotation={props.rotation}>
      <group name="Scene">
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.white}
          position={[0, -0.107, 0.388]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 0.1, 0.68]}>
          <mesh
            name="Torus"
            castShadow
            receiveShadow
            geometry={nodes.Torus.geometry}
            material={materials.black}
            position={[0.998, 0, 0.741]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.154, 0.227, 1.541]}
          />
          <mesh
            name="Torus001"
            castShadow
            receiveShadow
            geometry={nodes.Torus001.geometry}
            material={materials.black}
            position={[0.998, 0, 0.451]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.154, 0.227, 1.541]}
          />
          <mesh
            name="Torus002"
            castShadow
            receiveShadow
            geometry={nodes.Torus002.geometry}
            material={materials.black}
            position={[0.998, 0, 0.14]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.154, 0.227, 1.541]}
          />
          <mesh
            name="Torus003"
            castShadow
            receiveShadow
            geometry={nodes.Torus003.geometry}
            material={materials.black}
            position={[0.998, 0, -0.15]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.154, 0.227, 1.541]}
          />
          <mesh
            name="Torus004"
            castShadow
            receiveShadow
            geometry={nodes.Torus004.geometry}
            material={materials.black}
            position={[0.998, 0, -0.441]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.154, 0.227, 1.541]}
          />
          <mesh
            name="Torus005"
            castShadow
            receiveShadow
            geometry={nodes.Torus005.geometry}
            material={materials.black}
            position={[0.998, 0, -0.731]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.154, 0.227, 1.541]}
          />
        </mesh>
        <mesh
          name="pencil"
          castShadow
          receiveShadow
          geometry={nodes.pencil.geometry}
          material={materials.orange}
          position={[-0.388, 0, 0]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[-0.106, -0.589, -0.106]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/model/notes.glb')