/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function ReactM(props) {
  const { nodes, materials } = useGLTF('/model/react.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.react.geometry}
        material={materials.reactBlue}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/model/react.glb')
export default ReactM