/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

function Three(props) {
  const { nodes, materials } = useGLTF('/model/three.glb')
  return (
    <group {...props} dispose={null}>
      <mesh rotation={[0, 0, -0.2]}
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['white.001']}
      />
    </group>
  )
}

useGLTF.preload('/model/three.glb')
export default Three