/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { param } from '@/lib/param'
import Typo from "@/models/mesh/Typo"

function TS(props) {
  const { nodes, materials } = useGLTF('./model/TS.glb')
  return (
    <group {...props} dispose={null}>
      <Typo font={"Neutra_Book"} size={0.8} position={[-0.4, -0.8, 0]} color={param.white} height={0.3} text={"TS"} />
      <mesh
        geometry={nodes.ts.geometry}
        material={materials.ts}
        scale={[1, 1, 0.219]}
      />
    </group>
  )
}

useGLTF.preload('./model/TS.glb')
export default TS