/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useHelper } from '@react-three/drei'
import Thermometer from './WeatherThermometer'

export function Streetlight(props) {
  const { nodes, materials } = useGLTF('/model/streetlight.glb')
  const spotLightRef = useRef()
  const target = useRef()

  useEffect(() => {
    if (spotLightRef.current) spotLightRef.current.target = target.current
  }, [])

  //useHelper(spotLightRef, THREE.SpotLightHelper, '#fff')

  return (
    <group {...props}>
      <group dispose={null} position={[0.42, 0.01, -0.3]} rotation-y={-Math.PI * 0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar001.geometry}
          material={materials.streetlight}
          position={[0, 0.063, 0]}
          scale={[0.068, 0.022, 0.068]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hex.geometry}
          material={materials.streetlight}
          position={[0, 0.027, 0]}
          scale={[0.101, 0.035, 0.101]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lightHead.geometry}
          material={materials.streetlight}
          position={[0, 0.791, 0.188]}
          scale={[-0.05, -0.039, -0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.light.geometry}
          material={materials.light}
          position={[0, 0.791, 0.188]}
          scale={[-0.047, -0.038, -0.047]}
        >
          {props.hovered ?
            <meshBasicMaterial color="#ffea09" /> :
            <meshBasicMaterial color="#909090" />
          }
        </mesh>
      </group>

      <spotLight castShadow
        ref={spotLightRef}
        visible={props.hovered}
        position={[0.2, 0.8, -0.1]}
        angle={1.0}
        penumbra={0.5}
        intensity={200}
        distance={100}
        shadow-mapSize={[2048, 2048]}
        shadow-camera-near={0.1}
        shadow-camera-far={1}
        shadow-bias={-0.0001}
        shadow-normalBias={0.02}
      />

      <object3D ref={target} position={[0.2, -1, 0.5]} />
    </group>
  )
}

useGLTF.preload('/model/streetlight.glb')