/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame, useLoader } from '@react-three/fiber'

export default function Thermometer({ hovered }) {
  const { nodes, materials } = useGLTF('/model/thermometer.glb')
  const liquidRef = useRef()
  const liquidMaterialRef = useRef()
  const screenRef = useRef([])
  const tempValue = hovered ? 30 : 15

  const normalFace = useLoader(THREE.TextureLoader, '/weatherland/normal.png')
  const hotFace = useLoader(THREE.TextureLoader, '/weatherland/hot.png')

  useEffect(() => {
    if (!liquidMaterialRef.current) return

    let face

    if (hovered) face = hotFace
    else face = normalFace

    const color = hovered ? '#f87103' : '#25eb5a'

    screenRef.current.forEach(material => {
      if (!material) return

      material.map = face
      material.color.set(color)
      material.needsUpdate = true
    })

    liquidMaterialRef.current.color.set(color)
  }, [tempValue])

  useFrame((_, delta) => {
    delta = Math.min(delta, 0.05)
    if (!liquidRef.current) return

    const targetScale = THREE.MathUtils.mapLinear(
      tempValue ?? 0, -50, 50, -0.04, 0.04
    )

    liquidRef.current.scale.y = THREE.MathUtils.lerp(
      liquidRef.current.scale.y,
      targetScale,
      delta * 5
    )
  })

  return (
    <group dispose={null} scale={13} position={[2.8, -4.3, -2.2]} rotation-y={-Math.PI * 0.2}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.face.geometry}
        material={materials.streetlight}
        position={[0.062, 0.791, -0.001]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.026, 0.124, 0.026]}
      >
        <meshBasicMaterial
          ref={el => (screenRef.current[0] = el)}
          map={normalFace}
          transparent
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.face.geometry}
        material={materials.streetlight}
        position={[0.059, 0.791, -0.001]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.026, 0.124, 0.026]}
      >
        <meshBasicMaterial
          ref={el => (screenRef.current[1] = el)}
          map={normalFace}
          transparent
        />
      </mesh>

      <mesh ref={liquidRef}
        castShadow
        receiveShadow
        geometry={nodes.liquid.geometry}
        material={nodes.liquid.material}
        position={[0.06, 0.665, -0.001]}
        scale={[0.004, 0, 0.004]}
      >
        <meshBasicMaterial
          ref={liquidMaterialRef}
          color="#fff"
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thermometer_.geometry}
        material={materials.streetlight}
        position={[0.019, 0.757, -0.001]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass.geometry}
        material={nodes.glass.material}
        position={[0.06, 0.665, -0.001]}
        scale={[0.005, 0.085, 0.005]}
      >
        <meshStandardMaterial
          color="#ffffff"
          metalness={0.5}
          roughness={0.1}
          side={THREE.DoubleSide}
          transparent
          opacity={0.2}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass002.geometry}
        material={materials.streetlight}
        position={[0.06, 0.536, -0.001]}
        scale={[0.005, 0.085, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass001.geometry}
        material={materials.streetlight}
        position={[0.06, 0.676, -0.001]}
        scale={[0.005, 0.135, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen.geometry}
        material={materials.streetlight}
        position={[0.061, 0.791, -0.001]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.026, 0.124, 0.026]}
      />
    </group>
  )
}

useGLTF.preload('/model/thermometer.glb')