/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'

export default function Post() {
  const { nodes, materials } = useGLTF('/model/post.glb')
  const doorFront = useRef()
  const doorBack = useRef()
  const [hovered, setHovered] = useState(false)

  useEffect(() => {
    if (!doorFront.current || !doorBack.current) return

    gsap.to(doorFront.current.rotation, {
      x: hovered ? Math.PI / 2 : 0,
      duration: 0.5,
      ease: 'power2.out'
    })

    gsap.to(doorBack.current.rotation, {
      x: hovered ? Math.PI / 2 : Math.PI,
      duration: 0.5,
      ease: 'power2.out'
    })

  }, [hovered])

  return (
    <group dispose={null} position={[0.1, 0.02, -4.6]} scale={0.7}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillar002.geometry}
        material={materials.red}
        position={[0, 1.611, 0]}
        scale={[0.11, 1.8, 0.11]}
      />
      <group position={[0, 3.842, 0]} scale={[0.455, 0.455, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube422.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube422_1.geometry}
          material={materials.darkRed}
        />
      </group>
      <group position={[0, 3.722, 0]} scale={[0.518, 0.518, 0.794]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube423.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube423_1.geometry}
          material={materials.darkRed}
        />
      </group>
      <group ref={doorFront} position={[0, 3.386, 0.649]} scale={[0.455, 0.455, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube427.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube427_2.geometry}
          material={materials.darkRed}
        />
      </group>
      <group ref={doorBack}
        position={[0, 3.386, -0.64]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.455, 0.455, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube500.geometry} material={materials.red} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube500_2.geometry}
          material={materials.darkRed}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/model/post.glb')